import Navigations from '@/components/Navigations';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navigations />
        </header>
        {children}
      </body>
    </html>
  );
}
